enabled: true
endpoints:
  - host: kakotkin.ru
    path: /api
    reverseProxy:
      #host: localhost
      port: 12345
  - host: kakotkin.ru
    path: /
    static: 
      dir: ./static
      page404: 404.html # or index.html for SPA
  - host: apyr.ru
    path: /
    redirect: https://kakotkin.ru
