logs: /root/mws.log
certs: /root/certs.json
endpoints:
  - url: chat.apyr.ru
    https: true #default: true
    redirectToHttps: true #default: same as https
    proxy: tinode:8080

  - url: adminer-sys.apyr.ru
    https: false
    proxy: adminer:8080

  - url: static.apyr.ru/api
    proxy:
      to: my-api:8080
      removePrefix: /api

  - url: static.apyr.ru
    static: 
      dir: /root/static
      page404: /root/static/404.html
